name: Test API

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Ensure Cypress is installed
        run: |
          npx cypress install
          ls -la node_modules/.bin
          chmod +x node_modules/.bin/cypress
          npx cypress verify

      - name: Run API tests
        run: npx cypress run --env ambiente=hml
