name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ # Defina o diretório do projeto se necessário
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run API tests
        env:
          PARCEIRO: ${{ github.event.inputs.parceiro || 'placeholder' }}
          AMBIENTE: ${{ github.event.inputs.ambiente || 'hml' }}
        run: |
          echo "Parceiro: $PARCEIRO"
          echo "Ambiente: $AMBIENTE"
          npx cypress run --env parceiro=$PARCEIRO,ambiente=$AMBIENTE
