name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Cypress install
        run: npx cypress install

      - name: Run Cypress tests
        run: npm run cypress:run:tags
        env:
          PARCEIRO: placeholder
          AMBIENTE: hml
          grepTags: @recursos

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
