name: Test API

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Ensure Cypress is installed
        run: |
          npx cypress install
          ls -la node_modules/.bin
          chmod +x node_modules/.bin/cypress
          npx cypress verify

      - name: Run API tests
        run: npx cypress run --reporter cypress-multi-reporters --reporter-options configFile=reporter-config.json --env ambiente=hml

      - name: Generate Cucumber HTML Report
        run: node cypress/utils/cucumber-html-report.js

      - name: Upload Cucumber JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: cypress/reports/cucumber-json/

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: cypress/reports/cucumber-html-report.html
